### PR TITLE
Some enhancements

### PR DESCRIPTION
**Pull request by csoutham**
I've included a couple of extras:

- Enabling the content area customiser
- Support for ACF Pro if installed
- Full width padding removed
- Cache busting CSS and JS via theme version number

Let me know what you think!

### CODE REVIEW

**Comment by RaitisSevelis** [comment]
@AngeIII please review this and merge

**Comment by AngeIII** [comment]
@RaitisSevelis most changes are good. But some of commit changes paddings for container. This should be checked with design

**Comment by AngeIII** [comment]
@RaitisSevelis I mean
`.content-wrapper {
 -  padding: 45px 15px 1px 15px;
 +  padding: 0;
    margin: 0 -15px;
    overflow-wrap: break-word;
    background-color: #fff;
  }
  .main-content {
 -  padding-bottom: 40px;
 +  padding-bottom: 0;
  }`

**Comment by AngeIII** [comment]
@csoutham can you explain idea behind padding changes in `content-wrapper` and `main-content`

**Comment by csoutham** [comment]
@AngeIII just so you could have edge to edge full screen rows rather than be dictated that they must padding left and right. Also padding at the bottom is enforced rather than allowing you to add it if wanted via VC.

**Comment by AngeIII** [comment]
@csoutham please revert latest changes commit and we will merge all other changes into mainline. The padding changes should be pushed in separate pull request.

**Comment by csoutham** [comment]
To be honest, I'm not using the theme anymore - feel free to cherry pick or forget it.

**Pull request closed without merging**
